In [1]:
import pandas as pd
import matplotlib as plt

In [10]:
## Datasets to explore
df = pd.read_csv('../data/raw/fireprot_upload/csvs/4_fireprotDB_bestpH.csv', index_col=0)
split_train = pd.read_csv('../data/raw/fireprot_upload/csvs/splits/fireprot_train.csv', index_col=0)
split_test = pd.read_csv('../data/raw/fireprot_upload/csvs/splits/fireprot_test.csv', index_col=0)
split_val = pd.read_csv('../data/raw/fireprot_upload/csvs/splits/fireprot_val.csv', index_col=0)
split_homologue_free = pd.read_csv('../data/raw/fireprot_upload/csvs/splits/fireprot_homologue_free.csv', index_col=0)

In [6]:
df.head()

,experiment_id,protein_name,uniprot_id,pdb_id,chain,position,wild_type,mutation,ddG,dTm,...,hsw_job_id,datasets,sequence,pdb_id_corrected,dupe_detector,pdb_position,pdb_sequence,oligomeric_state,structure_method,resolution
23,LL000714,Immunoglobulin G-binding protein G,P06654,1PGA|1EM7|2GB1,A,1,M,A,-0.14,NaN,...,2i1nqi,NaN,MEKEKKVKYFLRKSAFGLASVSAAFLVGSTVFAVDSPIEDTPIIRN...,1PGA,1PGA-A-0-M-P06654,0,MTYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYD...,monomer,x-ray diffraction,NaN
24,LL000715,Immunoglobulin G-binding protein G,P06654,1PGA|1EM7|2GB1,A,1,M,D,-0.38,NaN,...,2i1nqi,NaN,MEKEKKVKYFLRKSAFGLASVSAAFLVGSTVFAVDSPIEDTPIIRN...,1PGA,1PGA-D-0-M-P06654,0,MTYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYD...,monomer,x-ray diffraction,NaN
25,LL000716,Immunoglobulin G-binding protein G,P06654,1PGA|1EM7|2GB1,A,1,M,E,-0.64,NaN,...,2i1nqi,NaN,MEKEKKVKYFLRKSAFGLASVSAAFLVGSTVFAVDSPIEDTPIIRN...,1PGA,1PGA-E-0-M-P06654,0,MTYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYD...,monomer,x-ray diffraction,NaN
26,LL000717,Immunoglobulin G-binding protein G,P06654,1PGA|1EM7|2GB1,A,1,M,F,-1.14,NaN,...,2i1nqi,NaN,MEKEKKVKYFLRKSAFGLASVSAAFLVGSTVFAVDSPIEDTPIIRN...,1PGA,1PGA-F-0-M-P06654,0,MTYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYD...,monomer,x-ray diffraction,NaN
27,LL000718,Immunoglobulin G-binding protein G,P06654,1PGA|1EM7|2GB1,A,1,M,G,-0.30,NaN,...,2i1nqi,NaN,MEKEKKVKYFLRKSAFGLASVSAAFLVGSTVFAVDSPIEDTPIIRN...,1PGA,1PGA-G-0-M-P06654,0,MTYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYD...,monomer,x-ray diffraction,NaN

In [8]:
df

,experiment_id,protein_name,uniprot_id,pdb_id,chain,position,wild_type,mutation,ddG,dTm,...,hsw_job_id,datasets,sequence,pdb_id_corrected,dupe_detector,pdb_position,pdb_sequence,oligomeric_state,structure_method,resolution
23,LL000714,Immunoglobulin G-binding protein G,P06654,1PGA|1EM7|2GB1,A,1,M,A,-0.14,NaN,...,2i1nqi,NaN,MEKEKKVKYFLRKSAFGLASVSAAFLVGSTVFAVDSPIEDTPIIRN...,1PGA,1PGA-A-0-M-P06654,0,MTYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYD...,monomer,x-ray diffraction,NaN
24,LL000715,Immunoglobulin G-binding protein G,P06654,1PGA|1EM7|2GB1,A,1,M,D,-0.38,NaN,...,2i1nqi,NaN,MEKEKKVKYFLRKSAFGLASVSAAFLVGSTVFAVDSPIEDTPIIRN...,1PGA,1PGA-D-0-M-P06654,0,MTYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYD...,monomer,x-ray diffraction,NaN
25,LL000716,Immunoglobulin G-binding protein G,P06654,1PGA|1EM7|2GB1,A,1,M,E,-0.64,NaN,...,2i1nqi,NaN,MEKEKKVKYFLRKSAFGLASVSAAFLVGSTVFAVDSPIEDTPIIRN...,1PGA,1PGA-E-0-M-P06654,0,MTYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYD...,monomer,x-ray diffraction,NaN
26,LL000717,Immunoglobulin G-binding protein G,P06654,1PGA|1EM7|2GB1,A,1,M,F,-1.14,NaN,...,2i1nqi,NaN,MEKEKKVKYFLRKSAFGLASVSAAFLVGSTVFAVDSPIEDTPIIRN...,1PGA,1PGA-F-0-M-P06654,0,MTYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYD...,monomer,x-ray diffraction,NaN
27,LL000718,Immunoglobulin G-binding protein G,P06654,1PGA|1EM7|2GB1,A,1,M,G,-0.30,NaN,...,2i1nqi,NaN,MEKEKKVKYFLRKSAFGLASVSAAFLVGSTVFAVDSPIEDTPIIRN...,1PGA,1PGA-G-0-M-P06654,0,MTYKLILNGKTLKGETTTEAVDAATAEKVFKQYANDNGVDGEWTYD...,monomer,x-ray diffraction,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6604,PT025496,Ribose import binding protein RbsB,P02925,2DRI,A,213,A,C,NaN,-6.60,...,jungim,EASE-MM-238|ProTherm,MNMKKLATLVSAVALSATVSANAMAKDTIALVVSTLNNPFFVSLKD...,2DRI,2DRI-C-187-A-P02925,187,KDTIALVVSTLNNPFFVSLKDGAQKEADKLGYNLVVLDSQNNPAKE...,monomer,x-ray diffraction,NaN
6605,PT025629,Ovalbumin,P01012,1UHG,A,143,R,A,NaN,-3.30,...,ufkeo8,ProTherm,MGSIGAASMEFCFDVFKELKVHHANENIFYCPIAIMSALAMVYLGA...,1UHG,1UHG-A-141-R-P01012,141,GSIGAASMEFCFDVFKELKVHHANENIFYCPIAIMSALAMVYLGAK...,monomer,x-ray diffraction,NaN
6606,PT025712,Cocaine esterase,Q9L9D7,1JU3,A,172,T,R,NaN,3.78,...,uznt1b,ProTherm,MVDGNYSVASNVMVPMRDGVRLAVDLYRPDADGPVPVLLVRNPYDK...,1JU3,1JU3-R-167-T-Q9L9D7,167,NYSVASNVMVPMRDGVRLAVDLYRPDADGPVPVLLVRNPYDKFDVF...,monomer,x-ray diffraction,NaN
6607,PT025713,Cocaine esterase,Q9L9D7,1JU3,A,173,G,Q,NaN,2.97,...,uznt1b,ProTherm,MVDGNYSVASNVMVPMRDGVRLAVDLYRPDADGPVPVLLVRNPYDK...,1JU3,1JU3-Q-168-G-Q9L9D7,168,NYSVASNVMVPMRDGVRLAVDLYRPDADGPVPVLLVRNPYDKFDVF...,monomer,x-ray diffraction,NaN
6608,PT025715,Cocaine esterase,Q9L9D7,1JU3,A,169,L,K,NaN,6.30,...,uznt1b,ProTherm,MVDGNYSVASNVMVPMRDGVRLAVDLYRPDADGPVPVLLVRNPYDK...,1JU3,1JU3-K-164-L-Q9L9D7,164,NYSVASNVMVPMRDGVRLAVDLYRPDADGPVPVLLVRNPYDKFDVF...,monomer,x-ray diffraction,NaN

In [11]:
splits = ['split_train', 'split_test', 'split_val', 'split_homologue_free']
for split in splits:
    print(f"{split}: {len(locals()[split])} samples")

split_train: 2686 samples
split_test: 350 samples
split_val: 402 samples
split_homologue_free: 2578 samples

In [12]:
## Working on the bestpH dataset first, to get a better understanding of the data.
df.info()

<class 'pandas.DataFrame'>
Index: 4997 entries, 23 to 6608
Data columns (total 42 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   experiment_id            4997 non-null   str
 1   protein_name             4997 non-null   str
 2   uniprot_id               4997 non-null   str
 3   pdb_id                   4997 non-null   str
 4   chain                    4997 non-null   str
 5   position                 4997 non-null   int64
 6   wild_type                4997 non-null   str
 7   mutation                 4997 non-null   str
 8   ddG                      3438 non-null   float64
 9   dTm                      1614 non-null   float64
 10  is_curated               4997 non-null   bool
 11  type                     0 non-null      float64
 12  derived_type             0 non-null      float64
 13  interpro_families        4989 non-null   str
 14  conservation             4309 non-null   float64
 15  is_essential             4997 non-null   bool
 16  correlated_positions     0 non-null      float64
 17  is_back_to_consensus     4997 non-null   bool
 18  secondary_structure      4465 non-null   str
 19  asa                      4465 non-null   float64
 20  is_in_catalytic_pocket   4997 non-null   bool
 21  is_in_tunnel_bottleneck  4997 non-null   bool
 22  b_factor                 4355 non-null   float64
 23  method                   4477 non-null   str
 24  method_details           3459 non-null   str
 25  technique                3459 non-null   str
 26  technique_details        3459 non-null   str
 27  pH                       4808 non-null   float64
 28  tm                       1956 non-null   float64
 29  notes                    1469 non-null   str
 30  publication_doi          4956 non-null   str
 31  publication_pubmed       4983 non-null   float64
 32  hsw_job_id               4772 non-null   str
 33  datasets                 3985 non-null   str
 34  sequence                 4997 non-null   str
 35  pdb_id_corrected         4997 non-null   str
 36  dupe_detector            4997 non-null   str
 37  pdb_position             4997 non-null   int64
 38  pdb_sequence             4997 non-null   str
 39  oligomeric_state         4997 non-null   str
 40  structure_method         4997 non-null   str
 41  resolution               0 non-null      float64
dtypes: bool(5), float64(12), int64(2), str(23)
memory usage: 4.6 MB

In [13]:
# Deletion of full null columns (type, derived_type etc.)
df = df.dropna(axis=1, how='all')

In [25]:
# Exploring some of the columns in more detail
df['asa'].value_counts()

asa
0.00     406
0.13     104
74.97     38
67.15     37
0.81      35
        ...
90.50      1
49.34      1
49.38      1
14.31      1
73.92      1
Name: count, Length: 1243, dtype: int64